AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CV Location Classifier - Serverless AI Travel Recommendation System
  
  Landmark detection, travel recommendations, and user authentication
  using AWS Lambda, API Gateway, and DynamoDB (Always Free Tier)

# ============================================================================
# GLOBAL CONFIGURATION
# ============================================================================
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Runtime: python3.11
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref LocationClassifierTable
        HUGGINGFACE_API_TOKEN: !Ref HuggingFaceAPIToken
        GROQ_API_KEY: !Ref GroqAPIKey
        JWT_SECRET: !Ref JWTSecret
        ALLOWED_ORIGINS: !Ref AllowedOrigins
        GOOGLE_APPLICATION_CREDENTIALS: !Ref GoogleCloudCredentials
    # Layers:
    #   - !Ref PythonDependenciesLayer
    #   - !Ref ModelsLayer
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Requested-With,Accept'"
      AllowOrigin: "'*'"
      AllowCredentials: false

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  HuggingFaceAPIToken:
    Type: String
    NoEcho: true
    Description: Hugging Face API token for CLIP embeddings
    
  GroqAPIKey:
    Type: String
    NoEcho: true
    Description: Groq API key for FREE fast vision model inference (Llama 4 Scout)
    
  GoogleCloudCredentials:
    Type: String
    NoEcho: true
    Description: Base64-encoded Google Cloud service account JSON for Vision API (Tier 3 fallback)
    Default: ""
    
  JWTSecret:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token signing (use strong random string)
    
  AllowedOrigins:
    Type: String
    Default: "*"
    Description: Comma-separated list of allowed CORS origins (e.g., https://myapp.com)

# ============================================================================
# RESOURCES
# ============================================================================
Resources:

  # ==========================================================================
  # LAMBDA LAYERS
  # ==========================================================================
  
  # Note: Lambda layers commented out for initial deployment
  # Models are too large (250MB+ limit). Will load from S3 or use lighter inference.
  # PythonDependenciesLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: cv-classifier-dependencies
  #     Description: Python dependencies (torch, transformers, fastapi, etc.)
  #     ContentUri: layers/python-dependencies/
  #     CompatibleRuntimes:
  #       - python3.11
  #     RetentionPolicy: Retain
  #   Metadata:
  #     BuildMethod: python3.11
  #     BuildArchitecture: x86_64

  # ModelsLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: cv-classifier-models
  #     Description: Trained models and landmark database
  #     ContentUri: layers/models/
  #     CompatibleRuntimes:
  #       - python3.11
  #     RetentionPolicy: Retain

  # ==========================================================================
  # API GATEWAY
  # ==========================================================================
  
  LocationClassifierAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: cv-location-classifier-api
      Description: REST API for CV Location Classifier
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        DefaultAuthorizer: NONE
      BinaryMediaTypes:
        - 'image/*'
        - 'multipart/form-data'

  # ==========================================================================
  # LAMBDA FUNCTIONS
  # ==========================================================================
  
  LocationClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cv-location-classifier
      Description: Main API handler for CV Location Classifier
      CodeUri: api/
      Handler: main.handler
      Timeout: 60
      MemorySize: 512  # Reduced from 3008 since model runs on HF Space
      Architectures:
        - x86_64
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: cv-location-classifier
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LocationClassifierTable
        - CloudWatchPutMetricPolicy: {}
        - S3ReadPolicy:
            BucketName: cv-classifier-embeddings
      # Enable Lambda Insights for enhanced monitoring (stays in free tier)
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
      Events:
        # Root
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /
            Method: GET
        
        # Health
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /health
            Method: GET
        
        # Info
        Info:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /info
            Method: GET
        
        # Auth endpoints
        Signup:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /auth/signup
            Method: POST
        
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /auth/login
            Method: POST
        
        PasswordResetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /auth/password-reset/request
            Method: POST
        
        PasswordResetConfirm:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /auth/password-reset/confirm
            Method: POST
        
        # User endpoints
        UserProfile:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /user/profile
            Method: GET
        
        # Prediction endpoints
        Predict:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /predict
            Method: POST
        
        PredictFallback:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /predict/fallback/{prediction_id}
            Method: POST
        
        PredictVisionAPI:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /predict/vision-api/{prediction_id}
            Method: POST
        
        # Recommendation endpoints
        Recommend:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /recommend
            Method: POST
        
        # Itinerary endpoints
        ItineraryAdd:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /itinerary/add
            Method: POST
        
        ItineraryList:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /itinerary/list
            Method: GET
        
        ItineraryDelete:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /itinerary/{itinerary_id}
            Method: DELETE
        
        # Feedback endpoints
        Feedback:
          Type: Api
          Properties:
            RestApiId: !Ref LocationClassifierAPI
            Path: /feedback
            Method: POST

  # ==========================================================================
  # CLOUDWATCH LOGGING
  # ==========================================================================
  
  LocationClassifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/cv-location-classifier
      RetentionInDays: 7  # Free tier: 5GB ingestion, 5GB archive per month

  # ==========================================================================
  # CLOUDWATCH ALARMS
  # ==========================================================================
  
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cv-location-classifier-errors
      AlarmDescription: Alert when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LocationClassifierFunction
      TreatMissingData: notBreaching

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cv-location-classifier-throttles
      AlarmDescription: Alert when Lambda function is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LocationClassifierFunction
      TreatMissingData: notBreaching

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cv-location-classifier-duration
      AlarmDescription: Alert when Lambda duration is high
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50000  # 50 seconds (timeout is 60)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LocationClassifierFunction
      TreatMissingData: notBreaching

  ApiGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cv-location-classifier-4xx-errors
      AlarmDescription: Alert on high rate of 4xx errors
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: cv-location-classifier-api
      TreatMissingData: notBreaching

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cv-location-classifier-5xx-errors
      AlarmDescription: Alert on high rate of 5xx errors
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: cv-location-classifier-api
      TreatMissingData: notBreaching

  # ==========================================================================
  # CLOUDWATCH DASHBOARD
  # ==========================================================================
  
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: cv-location-classifier-monitoring
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum", "label": "Invocations"}],
                  [".", "Errors", {"stat": "Sum", "label": "Errors"}],
                  [".", "Throttles", {"stat": "Sum", "label": "Throttles"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Invocations & Errors",
                "period": 300,
                "dimensions": {
                  "FunctionName": "${LocationClassifierFunction}"
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Duration", {"stat": "Average", "label": "Avg Duration"}],
                  ["...", {"stat": "Maximum", "label": "Max Duration"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Duration",
                "period": 300,
                "yAxis": {"left": {"label": "ms"}},
                "dimensions": {
                  "FunctionName": "${LocationClassifierFunction}"
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApiGateway", "Count", {"stat": "Sum", "label": "Total Requests"}],
                  [".", "4XXError", {"stat": "Sum", "label": "4xx Errors"}],
                  [".", "5XXError", {"stat": "Sum", "label": "5xx Errors"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Requests",
                "period": 300,
                "dimensions": {
                  "ApiName": "cv-location-classifier-api"
                }
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApiGateway", "Latency", {"stat": "Average", "label": "Avg Latency"}],
                  ["...", {"stat": "p99", "label": "P99 Latency"}]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Latency",
                "period": 300,
                "yAxis": {"left": {"label": "ms"}},
                "dimensions": {
                  "ApiName": "cv-location-classifier-api"
                }
              }
            },
            {
              "type": "log",
              "properties": {
                "query": "SOURCE '/aws/lambda/cv-location-classifier'\n| fields @timestamp, @message\n| filter @message like /ERROR/\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Errors",
                "stacked": false
              }
            }
          ]
        }

  # ==========================================================================
  # DYNAMODB TABLE
  # ==========================================================================
  
  LocationClassifierTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cv-location-app
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
        - AttributeName: GSI2_PK
          AttributeType: S
        - AttributeName: GSI2_SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2_PK
              KeyType: HASH
            - AttributeName: GSI2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Application
          Value: cv-location-classifier
        - Key: Environment
          Value: production

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${LocationClassifierAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
  
  ApiId:
    Description: API Gateway ID
    Value: !Ref LocationClassifierAPI
    Export:
      Name: !Sub "${AWS::StackName}-ApiId"
  
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt LocationClassifierFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref LocationClassifierFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
  
  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref LocationClassifierTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"
  
  DynamoDBTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt LocationClassifierTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TableArn"
  
  CloudWatchDashboard:
    Description: CloudWatch Dashboard URL
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=cv-location-classifier-monitoring"
  
  CloudWatchLogs:
    Description: CloudWatch Logs URL
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcv-location-classifier"
